### ISSUE TITLE
权限导致下载失败

### ISSUE THREAD

**Issue by duxun** [jenly1314/AppUpdater#10]
问题：读写权限未获取的情况下进行下载
状况：appupdater中有检测权限，但是通过后再下载apk的时候提示下载失败，点击通知栏重新下载后没有反应。

**Comment by jenly1314** [comment]
最好贴上相关日志。
说明：AppUpdater本应该只专注于App更新，尽量不涉及动态权限相关的处理。在你初始化AppUpdater时，如果Context传的是Activity，则默认会校验一次动态权限。
