### ISSUE TITLE
1.0.6版本弹窗设置拦截返回键无作用

### ISSUE THREAD

**Issue by bannerkun** [jenly1314/AppUpdater#14]

**Comment by jenly1314** [comment]
app-dialog你使用1.0.5吧。1.0.6版本不小心改错了一句代码导致没拦截，后续发布新版本修复。

**Comment by bannerkun** [comment]
老哥，为什么安装完，不删除本地已下载的文件，mFile.delete这句不会走，

**Comment by jenly1314** [comment]
没太听懂你的意思，是想安装后删除文件吗？

**Comment by bannerkun** [comment]
是的，我这边有出现一个清空，本地有apk,versioncode都不一样，还是吊起安装，导致下载不了最新版本。

**Comment by bannerkun** [comment]
我想安装新版本后删除下载的安装包，这样就不会出问题了

**Comment by jenly1314** [comment]
你应该是用了优先缓存机制吧，也就是：setVersionCode(int versionCode);中设置的versionCode需要与最新的apk版本一致。

**Comment by bannerkun** [comment]
setVersionCode的值是从服务器拿的，是最新apk的versionCode值。这样填写对吗？

**Comment by bannerkun** [comment]
我以前没设置versionCode对比 ，最近新版才加入的，会对就版本有影响吗？

**Comment by jenly1314** [comment]
没影响，设置了 **versionCode** 只是增加优先取缓存机制，相同版本的apk只下载一次，减少重复下载的动作。当本地存在与**versionCode**相同的apk时，就不会再重新去下载。
