### ISSUE TITLE
关于service内弹出dialog的建议

### ISSUE THREAD

**Issue by cjcj125125** [jenly1314/AppUpdater#16]
有的时候需要在service里面弹出dialog升级，那么这个时候你这个dialog的工具栏就不行了，建议在
AppDialog类里面提供方法返回Dialog 对象，这样可以通过
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            //8.0新特性
            AppDialog.INSTANCE.getWindow().setType(WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY - 1);
        } else {
            AppDialog.INSTANCE.getWindow().setType(WindowManager.LayoutParams.TYPE_TOAST);
        }
这两个方法，在service里面弹出dialog

**Comment by jenly1314** [comment]
好的，后续版本考虑增加一个获取Dialog的方法。
