### ISSUE TITLE
华为mate20  Android版本10 无法升级

### ISSUE THREAD

**Issue by wuconghui** [jenly1314/AppUpdater#17]
报错  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
经检查APP已经申请了读写文件权限。

**Comment by jenly1314** [comment]
**AppUpdater** 已适配了Android 10，默认并不需要读写权限。请给出更多的日志分析定位，或者使用**AppUpdater** 中的[Demo App](https://raw.githubusercontent.com/jenly1314/AppUpdater/master/app/release/app-release.apk)测试是否存在问题。

**Comment by wuconghui** [comment]
清单文件里 application标签添加 android:usesCleartextTraffic="true" 这样就可以了
