### ISSUE TITLE
设置setUpdateCallback后卡住

### ISSUE THREAD

**Issue by xingfukun** [jenly1314/AppUpdater#18]
设置setUpdateCallback后卡住，只执行了onDownloading以及onStart

**Comment by jenly1314** [comment]
你这样说没法帮你定位，请点击[![Download](https://img.shields.io/badge/download-App-blue.svg)](https://raw.githubusercontent.com/jenly1314/AppUpdater/master/app/release/app-release.apk) 下载Demo app看是否正常，或直接使用项目中的App例子程序运行起来看是否正常。
