### ISSUE TITLE
是否支持8.0

### ISSUE THREAD

**Issue by ppjuns** [jenly1314/AppUpdater#21]
在方法里面 com.king.app.updater.AppUpdater#startDownloadService 
我看else的逻辑会走启动服务的方法，mContext.startService(intent); 会不适配8.0
应该根据系统版本来启动startService 或 startForegroundService

**Comment by jenly1314** [comment]
你在什么场景下调用的？App升级的场景一般都是用户点升级的时候开始启动下载服务，此时APP并非在后台。
