### ISSUE TITLE
小米通知栏安装失败

### ISSUE THREAD

**Issue by phomel** [jenly1314/AppUpdater#28]

**Comment by jenly1314** [comment]
麻烦提供下手机型号，系统版本信息，相关日志等相关信息。

**Comment by phomel** [comment]
红米k40,  Android11.  没看到日志 . 有toast提示无法读取文件  访问被拒绝

**Comment by jenly1314** [comment]
> 红米k40, Android11. 没看到日志 . 有toast提示无法读取文件 访问被拒绝

我在MIUI12.5/ Android 11上验证过了，是正常的；因为没有提供相关日志，所以无法确定你的实际情况；请先下载 [演示App](https://raw.githubusercontent.com/jenly1314/AppUpdater/master/app/release/app-release.apk) 测试下看是否正常，以此来推断是否是集成的问题。
