### ISSUE TITLE
 Unable to build a new hidden directory

### ISSUE THREAD

**Issue by yyloveruancaipu** [jenly1314/AppUpdater#3]
android 8.0 
Unable to build a new hidden directory
java.io.FileNotFoundException: /storage/emulated/0/.AppUpdater/AppUpdater.apk (No such file or directory)

**Comment by jenly1314** [comment]
请确认是否允许了SDcard的读写权限，AppUpdater实例化的时候需要传Context，这个Context不强制要求是Activity，但能传Activity尽量传。AppUpdater本应该只专注于App更新，尽量不涉及动态权限相关的处理。如果Context传的是Activity默认会优先校验一次动态权限。
