### ISSUE TITLE
希望增加UpdateConfig设置下载的app的名字在Notification设置在“版本更新”前面

### ISSUE THREAD

**Issue by imhappyok** [jenly1314/AppUpdater#32]
希望增加UpdateConfig设置下载的app的名字在Notification设置在“版本更新”前面下显示，不然都不知道下载的是什么apk

**Comment by 13297063206** [comment]
我要是改就得直接导入moudle源码，不能直接implementation了

**Comment by jenly1314** [comment]
* 你这个需求在后续的版本中我会考虑看是否决定加入；因为从理论上说：通知栏的图标就基本能看出来是更新的哪个App。
* 如需修改通知栏标题提示，你只需在资源文件 **strings.xml** 中添加这两个配置即可，“版本更新” 要改成什么完全由你决定。

配置如下：
```
    <string name="app_updater_start_notification_title">版本更新</string>

    <string name="app_updater_progress_notification_title">版本更新</string>
```
