### ISSUE TITLE
如何在重新进入界面时能显示当前下载进度？

### ISSUE THREAD

**Issue by dylanZk1** [jenly1314/AppUpdater#36]

**Comment by jenly1314** [comment]
要在重新进入界面时监听下载进度需保证UpdateCallback是下载时设置的UpdateCallback同一个对象即可，这取决于你是怎么使用AppUpdater的；你可能需要声明一个单例的AppUpdater，在外部设置UpdateCallback更新回调，然后将下载进度使用广播发送或使用订阅者模式也行，最后在需要显示的界面接收当前下载进度。
