### ISSUE TITLE
框架内部的MD5值计算有问题

### ISSUE THREAD

**Issue by qaz2531883** [jenly1314/AppUpdater#38]
如果文件的MD5值的首位是0，框架内部计算出MD5值之后会自动去掉0，导致MD5值只有31位数了，一直无法匹配我设置进去的MD5值。
框架内打印的数据 D/AppUpdater: FileMD5:bc4af78bfaec50b820997444a3ce205

真正的MD5：0bc4af78bfaec50b820997444a3ce205

**Comment by jenly1314** [comment]
有空的时候，我确认下

**Comment by jenly1314** [comment]
请确认你使用的 **AppUpdater** 对应的版本，我验证了当前最新版本（v1.2.0），没有出现此问题。

**Comment by qaz2531883** [comment]
好的，我是1.1.3，回头我升至1.2.0

**Comment by qaz2531883** [comment]
刚刚看了一下1.2.0的源码，MD5值的计算方式确实改了。🐂
