### ISSUE TITLE
更新闪退

### ISSUE THREAD

**Issue by BaiMingxu** [jenly1314/AppUpdater#39]
报错如下
![CleanShot 2024-03-07 at 11 54 55@2x](https://github.com/jenly1314/AppUpdater/assets/22886455/a53d6707-f41b-4449-9a5c-45ec5ab3dc1d)

**Comment by jenly1314** [comment]
> 报错如下 ![CleanShot 2024-03-07 at 11 54 55@2x](https://private-user-images.githubusercontent.com/22886455/310743844-a53d6707-f41b-4449-9a5c-45ec5ab3dc1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTgzMDUsIm5iZiI6MTcwOTc5ODAwNSwicGF0aCI6Ii8yMjg4NjQ1NS8zMTA3NDM4NDQtYTUzZDY3MDctZjQxYi00NDQ5LTlhNWMtNDVlYzVhYjNkYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA3NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYmY0YWIyNjgzNGMwYjBiOWMxYTMwMGU2MWQ1MDdlYjY0YTNkYzZjMmY2Y2FmOTRjNWIyNDI4ZWJiNzlmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ox5sZtRnwz29e4h0xRQD0rVOGuo9yVGQE0VV7uas3A)

请尽量使用`AppUpdater`当前发布的最新版本；如果使用旧版本，麻烦先看下版本记录说明；你貌似使用是 **v1.1.3** 之前没适配Android 12的旧版本？

**Comment by BaiMingxu** [comment]
确实是版本问题，那之前老的版本就只能卸载手动安装了对吧

**Comment by jenly1314** [comment]
> 确实是版本问题，那之前老的版本就只能卸载手动安装了对吧

只能如此了。
*  当项目的 `targetSdk` 版本发生变化时，记得做适配。比如：更新第三方依赖；AppUpdater v1.1.3（适配Android 12）早在2022年就发布了。

**Comment by BaiMingxu** [comment]
谢谢
