### ISSUE TITLE
厂商纯净模式好像会直接闪退

### ISSUE THREAD

**Issue by 0xShawnLai** [jenly1314/AppUpdater#40]
如果用户开启了纯净模式，是不是就是缺少安装未知位置应用权限，能不能在内部做一个回调弹提示呢？

**Comment by jenly1314** [comment]
> 如果用户开启了纯净模式，是不是就是缺少安装未知位置应用权限，能不能在内部做一个回调弹提示呢？

反馈问题时靠谱一点，相关日志呢？
